import { DataStore } from './config/db.js';

const image = (id) => `https://images.unsplash.com/${id}?q=80&w=900&auto=format&fit=crop`;

const recipes = [
  {
    title: 'Creamy Garlic Chicken',
    description: 'Pan-seared chicken in a silky garlic parmesan sauce with wilted spinach.',
    ingredients: ['4 chicken breasts', '300 ml heavy cream', '5 garlic cloves, minced', '60 g parmesan, grated', '120 g baby spinach', '1 tbsp butter', '1 tbsp olive oil', '½ tbsp lemon juice', 'Salt, pepper & thyme'],
    instructions: [
      'Season and sear the chicken in a hot pan with butter and olive oil until golden, about 5 minutes per side.',
      'Bloom the minced garlic and thyme for 30 seconds without browning.',
      'Pour in the cream and parmesan, stirring until smooth and gently bubbling.',
      'Return the chicken to the sauce with its resting juices and spoon sauce over the tops.',
      'Fold in the spinach and cook until just wilted, 2–3 minutes.',
      'Finish with lemon juice and extra parmesan. Serve with crusty bread or rice.',
    ],
    category: 'Dinner',
    cookingTime: 35,
    difficulty: 'Medium',
    rating: 4.9,
    ratingCount: 212,
    image: image('photo-1604908176997-125f25cc6f3d'),
    authorName: 'Maya Anwar',
  },
  {
    title: 'Mediterranean Pasta',
    description: 'Cherry tomatoes, olives, feta and basil tossed through linguine.',
    ingredients: ['250 g linguine', '200 g cherry tomatoes', '100 g feta', '50 g kalamata olives', '2 cloves garlic', '4 tbsp olive oil', 'Fresh basil', 'Salt'],
    instructions: [
      'Boil the linguine in salted water until al dente, reserving a cup of pasta water.',
      'Sauté garlic and cherry tomatoes in olive oil until the tomatoes soften.',
      'Add olives, cooked pasta and a splash of pasta water; toss well.',
      'Crumble feta and tear fresh basil over the top before serving.',
    ],
    category: 'Dinner',
    cookingTime: 25,
    difficulty: 'Easy',
    rating: 4.8,
    ratingCount: 168,
    image: image('photo-1473093295043-cdd812d0e601'),
    authorName: 'Liam Costa',
  },
  {
    title: 'Avocado Breakfast Bowl',
    description: 'Creamy avocado, poached egg, cherry tomatoes and toasted seeds.',
    ingredients: ['2 avocados', '2 poached eggs', '100 g cherry tomatoes', '2 tbsp toasted seeds', 'Sourdough toast', 'Chili flakes', 'Lemon juice', 'Salt & pepper'],
    instructions: [
      'Mash the avocado with lemon juice, salt and chili flakes.',
      'Spoon the avocado into bowls and top with halved cherry tomatoes and poached eggs.',
      'Sprinkle with toasted seeds and serve with sourdough toast.',
    ],
    category: 'Breakfast',
    cookingTime: 15,
    difficulty: 'Easy',
    rating: 4.7,
    ratingCount: 96,
    image: image('photo-1525351484163-7529414344d8'),
    authorName: 'Nadia Hassan',
  },
  {
    title: 'Chocolate Lava Cake',
    description: 'Molten-center chocolate cakes with a light dusting of cocoa.',
    ingredients: ['150 g dark chocolate', '100 g butter', '2 eggs', '2 egg yolks', '80 g sugar', '40 g flour', 'Cocoa powder'],
    instructions: [
      'Melt the chocolate and butter together until smooth.',
      'Whisk eggs, yolks and sugar until pale, then fold in the chocolate.',
      'Fold in the flour and divide between buttered ramekins.',
      'Bake at 200°C for 10–12 minutes until the edges are set but the center is liquid.',
      'Rest for a minute, invert onto plates and dust with cocoa. Serve immediately.',
    ],
    category: 'Desserts',
    cookingTime: 40,
    difficulty: 'Hard',
    rating: 4.9,
    ratingCount: 184,
    image: image('photo-1606313564200-e75d5e30476c'),
    authorName: 'Sophie Laurent',
  },
  {
    title: 'Roasted Tomato Soup',
    description: 'Slow-roasted tomatoes blended with basil and a swirl of cream.',
    ingredients: ['800 g ripe tomatoes', '1 onion', '3 garlic cloves', '2 tbsp olive oil', '500 ml vegetable stock', 'Basil leaves', '50 ml cream', 'Salt & pepper'],
    instructions: [
      'Roast tomatoes, onion and garlic with olive oil at 200°C for 30 minutes.',
      'Blend the roasted vegetables with stock until smooth.',
      'Simmer for 10 minutes, season, then finish with cream and basil.',
    ],
    category: 'Quick Meals',
    cookingTime: 45,
    difficulty: 'Easy',
    rating: 4.6,
    ratingCount: 143,
    image: image('photo-1547592166-23ac45744acd'),
    authorName: 'Amira Khalid',
  },
  {
    title: 'Zucchini Fritters',
    description: 'Crisp golden fritters with garlic yogurt and fresh herbs.',
    ingredients: ['2 zucchini, grated', '60 g flour', '1 egg', '2 garlic cloves', '1 cup plain yogurt', 'Fresh dill', 'Salt & pepper', 'Olive oil for frying'],
    instructions: [
      'Grate the zucchini, squeeze out excess water and combine with flour, egg and seasoning.',
      'Spoon small patties into hot oil and fry until golden on both sides.',
      'Mix yogurt with garlic and dill, then serve with the fritters.',
    ],
    category: 'Vegan',
    cookingTime: 20,
    difficulty: 'Easy',
    rating: 4.5,
    ratingCount: 78,
    image: image('photo-1512621776951-a57141f2eefd'),
    authorName: 'Fatima Noor',
  },
  {
    title: 'Sourdough Pancakes',
    description: 'Fluffy sourdough pancakes topped with seasonal fruit and honey.',
    ingredients: ['200 g flour', '100 g sourdough starter', '250 ml milk', '1 egg', '1 tbsp sugar', '1 tsp baking soda', 'Seasonal fruit', 'Honey'],
    instructions: [
      'Whisk flour, starter, milk, egg and sugar into a smooth batter and rest for 10 minutes.',
      'Stir in the baking soda just before cooking.',
      'Fry in a buttered pan over medium heat until bubbles form, then flip.',
      'Stack high with fruit and a drizzle of honey.',
    ],
    category: 'Breakfast',
    cookingTime: 30,
    difficulty: 'Medium',
    rating: 4.8,
    ratingCount: 204,
    image: image('photo-1504754524776-8f4f37790ca0'),
    authorName: 'Elena Rossi',
  },
  {
    title: 'Lemon Herb Salmon',
    description: 'Oven-baked salmon fillets with lemon, dill and cracked pepper.',
    ingredients: ['4 salmon fillets', '1 lemon', '2 tbsp olive oil', 'Fresh dill', 'Cracked pepper', 'Salt'],
    instructions: [
      'Season the salmon and place on a lined baking tray.',
      'Top with lemon slices and drizzle with olive oil.',
      'Bake at 200°C for 12–14 minutes and finish with fresh dill.',
    ],
    category: 'Dinner',
    cookingTime: 22,
    difficulty: 'Easy',
    rating: 4.7,
    ratingCount: 131,
    image: image('photo-1467003909585-2f8a72700288'),
    authorName: 'Omar Farouk',
  },
  {
    title: 'Berry Pavlova',
    description: 'Crisp meringue, pillowy cream, and a tumble of fresh berries.',
    ingredients: ['4 egg whites', '220 g sugar', '1 tsp vinegar', '300 ml double cream', 'Mixed berries', 'Icing sugar'],
    instructions: [
      'Whisk egg whites with sugar until stiff, glossy peaks form.',
      'Fold in vinegar and spoon onto a lined tray into a nest shape.',
      'Bake low at 120°C for 90 minutes, then cool in the oven.',
      'Top with whipped cream and fresh berries, and dust with icing sugar.',
    ],
    category: 'Desserts',
    cookingTime: 90,
    difficulty: 'Hard',
    rating: 4.9,
    ratingCount: 221,
    image: image('photo-1560008581-09826d1de69e'),
    authorName: 'Hana Park',
  },
  {
    title: 'Vegan Buddha Bowl',
    description: 'Quinoa, roasted vegetables, hummus and tahini in one bowl.',
    ingredients: ['1 cup quinoa', '1 sweet potato', '1 zucchini', '200 g chickpeas', 'Hummus', 'Tahini', 'Spinach', 'Olive oil & spices'],
    instructions: [
      'Roast sweet potato, zucchini and chickpeas with olive oil and spices.',
      'Cook the quinoa in salted water until fluffy.',
      'Assemble bowls with quinoa, roasted vegetables, spinach, hummus and a tahini drizzle.',
    ],
    category: 'Vegan',
    cookingTime: 35,
    difficulty: 'Easy',
    rating: 4.6,
    ratingCount: 117,
    image: image('photo-1512058564366-18510be2db19'),
    authorName: 'Ines Berg',
  },
  {
    title: 'Crispy Tacos',
    description: 'Spiced fillings, crunchy shells, and quick-pickled slaw.',
    ingredients: ['8 taco shells', '400 g minced beef', '1 tbsp taco spice', '1 red onion', '1 cup red cabbage', 'Lime', 'Coriander', 'Sour cream'],
    instructions: [
      'Season the beef with taco spice and fry until crisp.',
      'Finely slice red cabbage and red onion, dress with lime juice and coriander.',
      'Fill warm shells with beef, slaw, and a dollop of sour cream.',
    ],
    category: 'Quick Meals',
    cookingTime: 25,
    difficulty: 'Medium',
    rating: 4.7,
    ratingCount: 158,
    image: image('photo-1565299624946-b28f40a0ae38'),
    authorName: 'Diego Alvarez',
  },
  {
    title: 'Wild Mushroom Risotto',
    description: 'Creamy arborio rice with porcini mushrooms and parmesan.',
    ingredients: ['300 g arborio rice', '250 g mixed mushrooms', '1 L warm stock', '1 onion', '1 glass white wine', '50 g parmesan', 'Butter', 'Thyme'],
    instructions: [
      'Sweat the onion in butter, add rice and toast briefly.',
      'Deglaze with wine, then add warm stock a ladle at a time while stirring.',
      'Fry the mushrooms separately and fold them in near the end.',
      'Finish with parmesan and butter, and rest for two minutes before serving.',
    ],
    category: 'Dinner',
    cookingTime: 55,
    difficulty: 'Hard',
    rating: 4.8,
    ratingCount: 196,
    image: image('photo-1476124369491-e7addf5db371'),
    authorName: 'Marco Bellini',
  },
];

export function seedIfEmpty() {
  if (DataStore.db.recipes.length > 0) return false;
  for (const r of recipes) {
    DataStore.insert('recipes', {
      id: DataStore.nextId('recipes'),
      ...r,
      imageAlt: r.title,
      authorId: null,
      authorName: r.authorName,
      createdAt: '2026-08-0' + String(1 + (r.title.length % 7)) + 'T09:00:00.000Z',
    });
  }
  return true;
}